# Generated by Django 3.1.4 on 2021-01-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
