# Generated by Django 3.1.4 on 2021-01-09 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('result', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='isCodeQuery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='codeQuery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.codequery'),
        ),
    ]
