# Generated by Django 3.1.4 on 2021-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210109_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
